export {
  ProjectHeader,
  ProjectPageLeftHeader,
  ProjectContainer,
  ProjectBackground,
  ProjectImage,
  ProjectSectionContent,
  ProjectDescContent,
  ProjectSectionHeading,
  ProjectSectionText,
  ProjectPageText,
  ProjectTextRow,
  ProjectSectionColumns,
  HonorTextRow,
  ProjectSection,
  ProjectImageSection,
} from './project';
